#!/usr/bin/env bash
# load_balancer-01 login commands

# Setting up the SSH agent
eval $("ssh-agent")

# Path to identityFile
ssh-add ~/.ssh/school

# Username and IP Address 
ssh ubuntu@44.205.245.205
